DROP MATERIALIZED VIEW IF EXISTS "public"."v08a_region_stats" CASCADE;--> statement-breakpoint
DROP MATERIALIZED VIEW IF EXISTS "public"."v07a_institute_stats" CASCADE;--> statement-breakpoint
DROP MATERIALIZED VIEW IF EXISTS "public"."v06a_edition_stats2" CASCADE;--> statement-breakpoint
DROP MATERIALIZED VIEW IF EXISTS "public"."v05a_edition_stats" CASCADE;--> statement-breakpoint
DROP MATERIALIZED VIEW IF EXISTS "public"."v04a_team_stats" CASCADE;--> statement-breakpoint
DROP MATERIALIZED VIEW IF EXISTS "public"."v03b_round_stats" CASCADE;--> statement-breakpoint
DROP MATERIALIZED VIEW IF EXISTS "public"."v02b_team_round_stats" CASCADE;--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."v02b_team_round_stats" AS (select "team_round"."id", COALESCE(sum("team_task_score"."score"), 0) as "total_scores", RANK() OVER (PARTITION BY "team_round"."round_id" ORDER BY COALESCE(sum("team_task_score"."score"), 0) DESC) as "rank_tot", RANK() OVER (PARTITION BY "team_round"."round_id", "institute"."region" ORDER BY COALESCE(sum("team_task_score"."score"), 0) DESC) as "rank_reg", CASE
                                  WHEN PERCENT_RANK() OVER (PARTITION BY "team_round"."round_id" ORDER BY COALESCE(sum("team_task_score"."score"), 0) DESC) = 0    THEN 0
                                  WHEN PERCENT_RANK() OVER (PARTITION BY "team_round"."round_id" ORDER BY COALESCE(sum("team_task_score"."score"), 0) DESC) <= 0.05 THEN 1
                                  WHEN PERCENT_RANK() OVER (PARTITION BY "team_round"."round_id" ORDER BY COALESCE(sum("team_task_score"."score"), 0) DESC) <= 0.15 THEN 2
                                  WHEN PERCENT_RANK() OVER (PARTITION BY "team_round"."round_id" ORDER BY COALESCE(sum("team_task_score"."score"), 0) DESC) <= 0.30 THEN 3
                                  ELSE null
                                END as "medal" from "team" inner join "edition" on ("edition"."id" = "team"."edition_id" and "edition"."public" = true) inner join "round" on ("round"."edition_id" = "edition"."id" and "round"."public" = true and ("team"."finalist" or "round"."slug" <> 'final')) left join "team_round" on ("team_round"."team_id" = "team"."id" and "team_round"."round_id" = "round"."id") left join "task" on "task"."round_id" = "round"."id" left join "team_task_score" on ("team_task_score"."team_id" = "team"."id" and "team_task_score"."task_id" = "task"."id") inner join "institute" on "institute"."id" = "team"."inst_id" where ("team"."junior" = false and not exists (select "team_round_penalization"."id" from "team_round_penalization" inner join "penalization" on "penalization"."id" = "team_round_penalization"."penalization_id" where ("team_round_penalization"."team_round_id" = "team_round"."id" and "penalization"."level" = 'yellow' and "penalization"."sent_at" is not null and ("penalization"."appeal_approved" is null or "penalization"."appeal_approved" = false))) and not exists (select "penalized_team_round"."id" from "team_round" "penalized_team_round" inner join "team_round_penalization" on "team_round_penalization"."team_round_id" = "penalized_team_round"."id" inner join "penalization" on "penalization"."id" = "team_round_penalization"."penalization_id" where ("penalized_team_round"."team_id" = "team"."id" and "penalization"."level" = 'red' and "penalization"."sent_at" is not null and ("penalization"."appeal_approved" is null or "penalization"."appeal_approved" = false)))) group by "team_round"."id", "institute"."region");--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."v03b_round_stats" AS (select "round"."id", count(distinct "team_round"."team_id") as "team_scored", COALESCE(sum("total_scores"), 0) as "total_scores", COALESCE(max("total_scores"), 0) as "max_score", COALESCE(avg("total_scores"), 0) as "avg_score", COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "total_scores"), 0) as "median_score" from "round" inner join "team_round" on "team_round"."round_id" = "round"."id" inner join "v02b_team_round_stats" on "v02b_team_round_stats"."id" = "team_round"."id" inner join "edition" on ("edition"."id" = "round"."edition_id" and "edition"."public" = true) where "total_scores" > 0 group by "round"."id");--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."v04a_team_stats" AS (select "team"."id", COALESCE(sum("total_scores"), 0) as "total_scores", RANK() OVER (PARTITION BY "team"."edition_id" ORDER BY COALESCE(sum("total_scores"), 0) DESC) as "rank_tot", RANK() OVER (PARTITION BY "team"."edition_id", "institute"."region" ORDER BY COALESCE(sum("total_scores"), 0) DESC) as "rank_reg", COALESCE(avg("rank_tot"), 0) as "avg_round_rank", COALESCE(min("rank_tot"), 0) as "best_round_rank", JSON_BUILD_OBJECT(
        0, COUNT(*) FILTER (WHERE "medal" = 0),
        1, COUNT(*) FILTER (WHERE "medal" = 1),
        2, COUNT(*) FILTER (WHERE "medal" = 2),
        3, COUNT(*) FILTER (WHERE "medal" = 3)
      ) as "total_medals" from "team" inner join "edition" on ("edition"."id" = "team"."edition_id" and "edition"."public" = true) inner join "round" on ("round"."edition_id" = "edition"."id" and "round"."public" = true and ("team"."finalist" = true or "round"."slug" <> 'final')) left join "team_round" on ("team_round"."team_id" = "team"."id" and "team_round"."round_id" = "round"."id") left join "v02b_team_round_stats" on "v02b_team_round_stats"."id" = "team_round"."id" inner join "institute" on "institute"."id" = "team"."inst_id" where ("team"."junior" = false and not exists (select "penalized_team_round"."id" from "team_round" "penalized_team_round" inner join "team_round_penalization" on "team_round_penalization"."team_round_id" = "penalized_team_round"."id" inner join "penalization" on "penalization"."id" = "team_round_penalization"."penalization_id" where ("penalized_team_round"."team_id" = "team"."id" and "penalization"."level" = 'red' and "penalization"."sent_at" is not null and ("penalization"."appeal_approved" is null or "penalization"."appeal_approved" = false)))) group by "team"."id", "team"."edition_id", "institute"."region");--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."v05a_edition_stats" AS (select "team"."edition_id", count(distinct "team"."id") as "total_teams", COALESCE(sum("total_scores"), 0) as "total_scores", COALESCE(max("total_scores"), 0) as "highest_score" from "v04a_team_stats" inner join "team" on "team"."id" = "v04a_team_stats"."id" inner join "edition" on ("edition"."id" = "team"."edition_id" and "edition"."public" = true) group by "team"."edition_id");--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."v06a_edition_stats2" AS (select "round"."edition_id", count(distinct "team"."inst_id") as "total_institutes", count(distinct "task"."id") as "total_tasks" from "v02b_team_round_stats" inner join "team_round" on "team_round"."id" = "v02b_team_round_stats"."id" inner join "team" on "team"."id" = "team_round"."team_id" inner join "task" on "task"."round_id" = "team_round"."round_id" inner join "round" on ("round"."id" = "team_round"."round_id" and "round"."public" = true) inner join "edition" on ("edition"."id" = "round"."edition_id" and "edition"."public" = true) group by "round"."edition_id");--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."v07a_institute_stats" AS (select "team"."inst_id", count(distinct "team"."edition_id") as "total_editions", count(distinct "team"."id") as "total_teams", COALESCE(sum(v02b_team_round_stats.total_scores), 0) as "total_scores", JSON_BUILD_OBJECT(
        0, COUNT(*) FILTER (WHERE v02b_team_round_stats.medal = 0),
        1, COUNT(*) FILTER (WHERE v02b_team_round_stats.medal = 1),
        2, COUNT(*) FILTER (WHERE v02b_team_round_stats.medal = 2),
        3, COUNT(*) FILTER (WHERE v02b_team_round_stats.medal = 3)
      ) as "total_medals", COALESCE(min(v04a_team_stats.rank_tot), 0) as "best_edition_rank", COALESCE(min(v02b_team_round_stats.rank_tot), 0) as "best_round_rank" from "v02b_team_round_stats" inner join "team_round" on "team_round"."id" = "v02b_team_round_stats"."id" inner join "team" on "team"."id" = "team_round"."team_id" inner join "v04a_team_stats" on "v04a_team_stats"."id" = "team"."id" inner join "round" on ("round"."id" = "team_round"."round_id" and "round"."public" = true) inner join "edition" on ("edition"."id" = "round"."edition_id" and "edition"."public" = true) group by "team"."inst_id");--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."v08a_region_stats" AS (select "institute"."region", count(distinct "edition"."id") as "total_editions", count(distinct "institute"."id") as "total_institutes", count(distinct "team"."id") as "total_teams", COALESCE(sum(v02b_team_round_stats.total_scores), 0) as "total_scores", JSON_BUILD_OBJECT(
        0, COUNT(*) FILTER (WHERE "medal" = 0),
        1, COUNT(*) FILTER (WHERE "medal" = 1),
        2, COUNT(*) FILTER (WHERE "medal" = 2),
        3, COUNT(*) FILTER (WHERE "medal" = 3)
      ) as "total_medals", COALESCE(min(v04a_team_stats.rank_tot), 0) as "best_edition_rank", COALESCE(min(v02b_team_round_stats.rank_tot), 0) as "best_round_rank" from "v02b_team_round_stats" inner join "team_round" on "team_round"."id" = "v02b_team_round_stats"."id" inner join "team" on "team"."id" = "team_round"."team_id" inner join "v04a_team_stats" on "v04a_team_stats"."id" = "team"."id" inner join "round" on ("round"."id" = "team_round"."round_id" and "round"."public" = true) inner join "edition" on ("edition"."id" = "round"."edition_id" and "edition"."public" = true) inner join "institute" on "institute"."id" = "team"."inst_id" group by "institute"."region");